# Generated by Django 6.0.6 on 2026-06-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Rent', 'Rent'), ('Hostel Rent', 'Hostel Rent'), ('Mess Fee', 'Mess Fee'), ('Travel Expenses', 'Travel Expenses'), ('Tuition Fee', 'Tuition Fee'), ('Stationery & Books', 'Stationery & Books'), ('Pocket Money', 'Pocket Money'), ('Utilities', 'Utilities'), ('Entertainment', 'Entertainment'), ('Salary', 'Salary'), ('Freelance', 'Freelance'), ('Others', 'Others')], default='Others', max_length=50),
        ),
    ]
